### ISSUE TITLE
Unhandled Exception error on right-click

### ISSUE THREAD

**Issue by darthfrankfurt** [SuperGouge/ChanThreadWatch#89]
I'm a long-time user of this program, but until today I was still using 1_16_0. Just downloaded 1_17_1 and ran it and added a link to test it. I found that upon right-clicking the entry, an error appeared. Here's the contents of the dialogue box:
_____________________________________________________________
************** Exception Text **************
System.ArgumentException: ContextMenu cannot be shown on an invisible control.
Parameter name: control
   at System.Windows.Forms.ContextMenu.Show(Control control, Point pos, Int32 flags)
   at JDP.frmChanThreadWatch.lvThreads_MouseClick(Object sender, MouseEventArgs e)
   at System.Windows.Forms.Control.OnMouseClick(MouseEventArgs e)
   at System.Windows.Forms.ListView.WmReflectNotify(Message& m)
   at System.Windows.Forms.ListView.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
_______________________________________________________________
A similar error was reported in 2014 here https://github.com/SuperGouge/ChanThreadWatch/issues/3 but was closed because the reporter couldn't reproduce the issue to get the information needed, which was the 13 lines starting with the problematic thread URL in threads.txt. So here they are:
_______________________________________________________________
https://boards.4channel.org/vp/thread/37616051

60
0
4channel_vp_37616051

4channel_vp_37616051
636868133824868128
636868133835667644

0
________________________________________________________________
Thank you for maintaining this awesome program. Hope this helps!
EDIT: I should clarify that I can't reproduce this error with version 1_16_0.

**Comment by jwshields** [comment]
fwiw I added that thread you listed and cannot reproduce the issue on 1.17.1, added removed category, stopped, started the thread, removed & remove + delete folder
